CREATE SCHEMA postgres;

GRANT USAGE, CREATE ON SCHEMA public TO PUBLIC;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO PUBLIC;

GRANT ALL PRIVILEGES ON SCHEMA postgres TO postgres;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA postgres TO postgres;

--GRANT ALL PRIVILEGES ON SCHEMA postgres TO mccusa; only for prod DB
--GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA postgres TO mccusa; only for prod DB
